linters:
  enable-all: true
  disable:
    - goimports
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - gomnd
    - gomodguard
    - exhaustivestruct

linters-settings:
  funlen:
    lines: 300
    statements: 170
  gocyclo:
    min-complexity: 70
  gocognit:
    min-complexity: 70
  nestif:
    min-complexity: 50
run:
  timeout: 3m

issues:
  exclude-use-default: true
