version: 3
services:
  db-test:
    container_name: db-test
    image: mariadb:10.5.8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-test:/var/lib/mysql
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
          "--default-authentication-plugin=mysql_native_password"
      ]

volumes:
  db-test:
