name: reviewdog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-consistent:
    name: runner / go-consistent
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: go-consistent
        uses: go-consistent/action-golangci-lint@v1

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.0.2
